In [3]:
import numpy as np

In [7]:
l=[1,2,3,4,5,6]
print (type(l))
arr=np.array(l)
print (type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
#### creating a sample array in numpy

In [11]:
arr=np.array([1,2,3,4])
print (arr)
print (type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [53]:
arr=np.array([1,2,3,4,5,6])
print (arr.ndim) # to no.dimensions
print (arr.shape)#to know shape of aaray
print (len(arr))#to know length of aaray
print (arr.dtype)#to know d.type
print (arr.itemsize)# to know size of aaray

1
(6,)
6
int32
4


In [61]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,1,5,8]])
print (arr.ndim) # to no.dimensions
print (arr.shape)#to know shape of aaray
print (len(arr))#to know length of aaray
print (arr.dtype)#to know d.type
print (arr.itemsize)# to know size of aaray

2
(2, 6)
2
int32
4


###### functions for creating Array

In [99]:
arr=np.ones((4,4))
print (arr)
print (arr.dtype)
print (arr.itemsize)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
8


In [87]:
arr=np.eye (3)  #identity matrix
print (arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
import numpy as np

In [11]:
arr =np.arange (10)
print (arr)
print (type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [15]:
#### arrange values by choice

In [21]:
arr=np.arange(10) # it takes by index values
print (arr)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
arr=np.arange (10,100)
print (arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [17]:
arr =np.arange (10,100,5) #10,100 in b/w  we skips 5 
print (arr)
print (type(arr))

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
<class 'numpy.ndarray'>


#### random numbers"

In [34]:
arr=np.random.rand(10) # it'll gives only 0,1 in b/w values
print (arr)

[0.61015729 0.15864576 0.95730136 0.64880909 0.18092223 0.61659805
 0.90684611 0.81143363 0.12042803 0.25902976]


In [36]:
#### numpy slicing

In [55]:
arr=np.arange (10)
print (arr)
print (arr[::3]) # stepping fun 

[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]


In [57]:
##### mathemaatical operation in numpy


In [61]:
x=([[2,4],[5,8]])
y=([[3,6],[7,9]])
print (np.add(x,y))

[[ 5 10]
 [12 17]]


In [63]:
x=([[2,4],[5,8]])
y=([[3,6],[7,9]])
print (np.subtract(x,y))


[[-1 -2]
 [-2 -1]]


In [65]:
x=([[2,4],[5,8]])
y=([[3,6],[7,9]])
print (np.multiply(x,y))

[[ 6 24]
 [35 72]]


In [67]:
x=([[2,4],[5,8]])
y=([[3,6],[7,9]])
print (np.divide(x,y))

[[0.66666667 0.66666667]
 [0.71428571 0.88888889]]


In [5]:
import numpy as np

In [13]:
x=np.array ([[1,2],[3,4]])
print (np.sum(x))        

10


In [15]:
x=np.array ([[1,2],[3,4]])
print (np.sum(x,axis=0))  #axis=0  means column wise operation

[4 6]


In [17]:
x=np.array ([[1,2],[3,4]])
print (np.sum(x,axis=1)) # axis=1   means row wise operation

[3 7]


In [19]:
x=np.array ([[1,2],[3,4]])
print (np.min(x))        

1


In [21]:
x=np.array ([[1,2],[3,4]])
print (np.max(x))        

4


##### transpose

In [28]:
x=np.array ([[1,2],[3,4]]) # rows into cloumn, col into row
print (x.T)        

[[1 3]
 [2 4]]


##### numpy reshape

In [59]:
import numpy as np

In [37]:
arr=np.arange(0,50,4)
print (arr)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48]


In [84]:
print (np.linspace(5,100,10))  # used to dive numbers equally 

[  5.          15.55555556  26.11111111  36.66666667  47.22222222
  57.77777778  68.33333333  78.88888889  89.44444444 100.        ]


In [100]:
#######Sorting

In [108]:
arr=np.random.randint(50,100,(5,10))
print (arr)
np.sort(arr,axis=0)
print ("*****************************************")
np.sort(arr,axis=1)

[[55 91 51 53 70 71 59 67 55 73]
 [69 80 85 85 86 72 86 55 98 79]
 [63 52 69 53 73 62 58 50 99 58]
 [56 65 99 96 73 72 74 59 94 82]
 [66 78 96 54 75 73 52 58 55 54]]
*****************************************


array([[51, 53, 55, 55, 59, 67, 70, 71, 73, 91],
       [55, 69, 72, 79, 80, 85, 85, 86, 86, 98],
       [50, 52, 53, 58, 58, 62, 63, 69, 73, 99],
       [56, 59, 65, 72, 73, 74, 82, 94, 96, 99],
       [52, 54, 54, 55, 58, 66, 73, 75, 78, 96]])

In [134]:
#### stack arange in vertical & horizontal - to find something or to search

In [124]:
arr=np.random.randint(50,100,(5,10))
print (arr)
np.vstack(arr)
np.where (arr>64,0,arr)

[[65 61 72 74 74 65 87 68 59 66]
 [87 59 79 70 73 88 85 62 97 89]
 [82 79 53 72 88 61 84 98 69 71]
 [97 71 80 99 77 81 80 92 55 66]
 [67 69 99 53 60 93 67 55 50 51]]


array([[ 0, 61,  0,  0,  0,  0,  0,  0, 59,  0],
       [ 0, 59,  0,  0,  0,  0,  0, 62,  0,  0],
       [ 0,  0, 53,  0,  0, 61,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 55,  0],
       [ 0,  0,  0, 53, 60,  0,  0, 55, 50, 51]])

In [132]:
arr=np.random.randint(50,100,(5,10))
print (arr)
np.hstack(arr)
np.where(arr<70,1,arr)

[[62 68 80 80 96 70 97 84 66 56]
 [58 82 52 79 83 72 58 64 79 63]
 [73 50 70 68 82 76 89 58 61 78]
 [85 95 57 60 70 55 70 72 53 53]
 [62 59 61 79 51 85 50 70 69 78]]


array([[ 1,  1, 80, 80, 96, 70, 97, 84,  1,  1],
       [ 1, 82,  1, 79, 83, 72,  1,  1, 79,  1],
       [73,  1, 70,  1, 82, 76, 89,  1,  1, 78],
       [85, 95,  1,  1, 70,  1, 70, 72,  1,  1],
       [ 1,  1,  1, 79,  1, 85,  1, 70,  1, 78]])